# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField(default=False)),
                ('IDmedico', models.CharField(max_length=20)),
                ('disponible', models.BooleanField(default=False)),
                ('IDpaciente', models.CharField(default='-1', max_length=20)),
            ],
        ),
    ]
